### ISSUE TITLE
4 Candles

### ISSUE THREAD

**Issue by lolobyte** [Jopyth/MMM-Advent#1]
possible to implement the possibility for choosing 4 candles with her own start and end days?

I can only arrange 3 candles with 3 modules in one level.

Yo know; bottom_left, bottom_center and bottom_right.

More is not possible!

**Comment by Jopyth** [comment]
I will look into it tonight.

**Comment by Jopyth** [comment]
Added in version 1.0.2 (use an array of timestamps - see the example below):


## [1.0.2] - 2016-12-04
### Changed
- Configuration options:
    - `start` and `end` can be an array of timestamps now
    - if they are, multiple candles are created side by side, one for each element in both arrays (length of both arrays should match)
    - Example for four red candles, lightning up at each advent sunday (disable animation with `enableAnimation: false,` if the flicker does not look nice):
```javascript
    {
        module: "MMM-Advent",
        position: "bottom_center",
        config: {
            marks: 0,
            candleColor: "#EE1111",
            start: ["2016-11-27 14:00:00", "2016-12-04 14:00:00", "2016-12-11 14:00:00", "2016-12-18 14:00:00"],
            end: ["2016-12-24 22:00:00", "2016-12-24 22:00:00", "2016-12-24 22:00:00", "2016-12-24 22:00:00"]
        }
    },
```

**Comment by lolobyte** [comment]
Thank u.
